### ISSUE TITLE
grabcartoons on Windows 10

### ISSUE THREAD

**Issue by DavidAccola** [zzamboni/grabcartoons#11]
When I try to run grabcartoons via perl and the Windows command line (Windows 10, specifically), I'm not able to get anywhere. Example:

C:\zzamboni-grabcartoons-0e67596>perl grabcartoons.pl xkcd > output.html
Can't exec /bin/sh at grabcartoons.pl line 1.

C:\zzamboni-grabcartoons-0e67596>perl grabcartoons.pl
Can't exec /bin/sh at grabcartoons.pl line 1.

C:\zzamboni-grabcartoons-0e67596>perl grabcartoons.pl -h
Can't exec /bin/sh at grabcartoons.pl line 1.

**Comment by zzamboni** [comment]
@DavidAccola I do not have a Windows machine, but can you try removing the first 3 lines of grabcartoons.pl and try again? These are the lines that should be removed:
```
#!/bin/sh
eval 'exec perl -x $0 ${1+"$@"}' # -*-perl-*-
  if 0;
```

**Comment by msaxer** [comment]
@DavidAccola Taking those initial lines out, as well as the later lines referencing $HOME, allowed me to run warning-free on Windows 10.

**Comment by zzamboni** [comment]
@msaxer thanks for the information. I have added a link to this issue from the README so others can find it.
